[tool.poetry]
name = "pyrosimple"
version = "1.2.0"
description = ""
authors = ["rallyemax <coloradan@gmail.com>"]
repository = "https://github.com/rallyemax/pyrosimple"
readme = "README.md"
classifiers = [
        "Development Status :: 3 - Alpha",
        "Environment :: Console",
        "Natural Language :: English",
        "Operating System :: POSIX",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Communications :: File Sharing",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">3.6,<4"
Tempita = "^0.5.2"
"bencode.py" = "^4.0.0"
APScheduler = {version = "^3.9.0", optional = true}
pyinotify = {version = "^0.9.6", optional = true}

[tool.poetry.extras]
torque = ["APScheduler", "pyinotify"]

[tool.poetry.scripts]
rtxmlrpc = "pyrosimple.scripts.rtxmlrpc:run"
rtcontrol = "pyrosimple.scripts.rtcontrol:run"
lstor = "pyrosimple.scripts.lstor:run"
chtor = "pyrosimple.scripts.chtor:run"
mktor = "pyrosimple.scripts.mktor:run"
pyrotorque = "pyrosimple.scripts.pyrotorque:run"
pyroadmin = "pyrosimple.scripts.pyroadmin:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
